export const RANKING = {
  EXACT_TITLE_MATCH: 120,
  TITLE_PREFIX_MATCH: 80,
  EXACT_HOST_MATCH: 70,
  HOST_PREFIX_MATCH: 60,
  PINNED_BONUS: 8,
  CURRENT_TAB_PENALTY: 20,
  MRU_TOP_1: 30,
  MRU_TOP_2: 24,
  MRU_TOP_3: 18,
  MINIMUM_INCLUDED_SCORE: 1,
} as const;
